### ISSUE TITLE
[JXR-26] NPE when source code contains quoted strings "package" or "import"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jxr#164]
**[Géraud Dugé](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gduge)** opened **[JXR-26](https://issues.apache.org/jira/browse/JXR-26?redirect=false)** and commented

Here is a sample code:

```
package fr.test;

public class SimpleTest
{
    public void test()
    {
    	//String varTest = "import";
    	String varTest = "package";
    }
}
```

When I run mvn jxr:jxr, the following NPE happens:

> ...
> [DEBUG] parsing... fr\test\SimpleTest.java
> [INFO] ------------------------------------------------------------------------
> [ERROR] FATAL ERROR
> [INFO] ------------------------------------------------------------------------
> [INFO] null
> [INFO] ------------------------------------------------------------------------
> [DEBUG] Trace
> java.lang.NullPointerException
> at org.apache.maven.jxr.pacman.JavaFileImpl.parse(JavaFileImpl.java:95)
> at org.apache.maven.jxr.pacman.JavaFileImpl.\<init>(JavaFileImpl.java:64)
> at org.apache.maven.jxr.pacman.FileManager.getFile(FileManager.java:68)
> ...

---

**Affects:** 1.0

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This was fixed in r516976.

**Comment by jira-importer** [comment]
**[Francis De Brabandere](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=francisdb)** commented

info:

If you encounter this issue you are probably still using

\<groupId>org.codehaus.mojo\</groupId>
\<artifactId>jxr-maven-plugin\</artifactId>

instead of

\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-jxr-plugin\</artifactId>
