### ISSUE TITLE
[JXR-32] JXR does not handle empty (completely commented) java-files...

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jxr#205]
**[Jan Palmquist](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jan.palmquist)** opened **[JXR-32](https://issues.apache.org/jira/browse/JXR-32?redirect=false)** and commented

I have detected that the jxr-plugin (or sub components) does not handle java-files being completely commented away e.g.
//package my.demopackage;
//public class MyClass {
//}

This is not a big issue, however it is quite annoying to have to notify developers that this not only is bad coding style but also breaks site generation.

My stack trace:
INFO] Generate "Test Source Xref" report.
Unable to processPath C:\CC\projects\MyProject\src\test\java\my\demopackage\MyClass.java => c:\CC\projects\MyProject\target/site/xref-test\my\demopackage\MyClass.html
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.jxr.JavaCodeTransform.getHeader(JavaCodeTransform.java:651)
at org.apache.maven.jxr.JavaCodeTransform.transform(JavaCodeTransform.java:716)
at org.apache.maven.jxr.JavaCodeTransform.transform(JavaCodeTransform.java:787)
at org.apache.maven.jxr.JXR.transform(JXR.java:195)
at org.apache.maven.jxr.JXR.processPath(JXR.java:114)
at org.apache.maven.jxr.JXR.xref(JXR.java:335)
at org.apache.maven.plugin.jxr.AbstractJxrReport.createXref(AbstractJxrReport.java:226)
at org.apache.maven.plugin.jxr.AbstractJxrReport.executeReport(AbstractJxrReport.java:352)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:67)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:239)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:115)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:124)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:92)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:420)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:330)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:123)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9 minutes 24 seconds
[INFO] Finished at: Thu Mar 22 07:26:14 CET 2007
[INFO] Final Memory: 73M/200M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This has already been fixed by previous commits. I created a small project for this and verified that I got an NPE when running 'mvn site'. Using the same project with maven-jxr-plugin 2.1-SNAPSHOT I do not get the NPE anymore.
